name: Geometric Lib
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
          uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.*
      - name: Setup Environment
        run: pip install -r requirements.txt
      - name: Test
        run: python.exe -m unittest tests.py